// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input [7:0] v6ff771,
 input v7c3028,
 output v5ea67d
);
 wire w0;
 wire w1;
 wire [0:7] w2;
 assign v5ea67d = w0;
 assign w1 = v7c3028;
 assign w2 = v6ff771;
 main_v168b7a v168b7a (
  .fq(w0),
  .Clk_i(w1),
  .ADC(w2)
 );
endmodule


module main_v168b7a (
 input [7:0] ADC,
 input Clk_i,
 output fq
);
 
 reg [31:0] Co;
 reg f = 0;
 // reg [15:0] traget = 100 + ADC;
 reg [31:0] limit = 12000000 / (2 * (100 + ADC));
 
 always @(posedge Clk_i) begin
     Co <= Co + 1;
     if(Co >= limit - 1) begin
         Co <= 0;
         f <= ~f;
     end
 end
 assign fq = f;
endmodule
