// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main #(
 parameter vb35d0c = 115200
) (
 input [3:0] v169a21,
 input va5d540,
 output [3:0] v748a5a,
 output vbab60c
);
 localparam p2 = vb35d0c;
 wire [0:3] w0;
 wire w1;
 wire [0:7] w3;
 wire w4;
 wire [0:3] w5;
 wire [0:3] w6;
 wire w7;
 wire w8;
 assign v748a5a = w0;
 assign vbab60c = w1;
 assign w4 = va5d540;
 assign w5 = v169a21;
 assign w8 = va5d540;
 assign w8 = w4;
 vc6459c #(
  .ved2ada(p2)
 ) vc7e5aa (
  .v8caaa5(w1),
  .v19b8dd(w3),
  .v05e99b(w7),
  .ve9a78f(w8)
 );
 v73122e vb20f4f (
  .vdeb67e(w5),
  .va8f67e(w6)
 );
 main_vb78d31 vb78d31 (
  .row(w0),
  .Value(w3),
  .Clk_i(w4),
  .col(w6),
  .txmit(w7)
 );
endmodule

//---- Top entity
module vc6459c #(
 parameter ved2ada = 115200
) (
 input ve9a78f,
 input [7:0] v19b8dd,
 input v05e99b,
 output v8caaa5,
 output v2da441,
 output v01321e
);
 localparam p1 = ved2ada;
 wire w0;
 wire w2;
 wire [0:7] w3;
 wire w4;
 wire w5;
 wire w6;
 assign v8caaa5 = w0;
 assign w2 = ve9a78f;
 assign w3 = v19b8dd;
 assign w4 = v05e99b;
 assign v2da441 = w5;
 assign v01321e = w6;
 vc6459c_vedebcc #(
  .BAUD(p1)
 ) vedebcc (
  .TX(w0),
  .clk(w2),
  .data(w3),
  .txmit(w4),
  .busy(w5),
  .done(w6)
 );
endmodule

//---------------------------------------------------
//-- Serial-tx
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Transmisor serie
//---------------------------------------------------

module vc6459c_vedebcc #(
 parameter BAUD = 0
) (
 input clk,
 input [7:0] data,
 input txmit,
 output TX,
 output busy,
 output done
);
 //-- Constantes para obtener las velocidades estándares
 `define B115200 104 
 `define B57600  208
 `define B38400  313
 `define B19200  625
 `define B9600   1250
 `define B4800   2500
 `define B2400   5000
 `define B1200   10000
 `define B600    20000
 `define B300    40000
 
 //-- Constante para calcular los baudios
 localparam BAUDRATE = (BAUD==115200) ? `B115200 : //-- OK
                       (BAUD==57600)  ? `B57600  : //-- OK
                       (BAUD==38400)  ? `B38400  : //-- Ok
                       (BAUD==19200)  ? `B19200  : //-- OK
                       (BAUD==9600)   ? `B9600   : //-- OK
                       (BAUD==4800)   ? `B4800   : //-- OK 
                       (BAUD==2400)   ? `B2400   : //-- OK
                       (BAUD==1200)   ? `B1200   : //-- OK
                       (BAUD==600)    ? `B600    : //-- OK
                       (BAUD==300)    ? `B300    : //-- OK
                       `B115200 ;  //-- Por defecto 115200 baudios
 
 
 //---- GENERADOR DE BAUDIOS
 
 //-- Calcular el numero dde bits para almacenar el divisor
 localparam N = $clog2(BAUDRATE);
 
 //-- Contador para implementar el divisor
 //-- Es un contador modulo BAUDRATE
 reg [N-1:0] divcounter = 0;
 
 //-- Cable de reset para el contador
 //-- Comparador que resetea el contador cuando se alcanza el tope
 //-- o cuando el estado del biestable es 0 (apagado)
 wire reset = ov_gen | (state == 0);
 
 //-- Contador con reset
 always @(posedge clk)
   if (reset)
     divcounter <= 0;
   else
     divcounter <= divcounter + 1;
 
 //-- Hemos llegado al final
 wire ov_gen = (divcounter == BAUDRATE-1);
 
 
 
 //-- REGISTRO DESPLAZAMIENTO
 
 //-- Salida serie. Inicialmete a 1 (reposo) 
 reg TX = 1;
 
 //-- Registro de desplazamiento de 9 bits
 //-- Inicializado todo a 1s
 reg [8:0] q = 9'h1FF;
 
 //-- La entrada de shift es la salida del generador de baudios
 wire shift = ov_gen;
 
 always @(posedge clk)
   if (txmit_tic)
   //-- Carga del registro
     q <= {data, 1'b0};
     
   else if (shift)
     //-- Desplazamiento. Rellenar con 1 (bit de stop)
     q <= {1'b1, q[8:1]};
     
 //-- Sacar el bit de menor peso por serial-out    
 wire so;
 assign so = q[0];
 
 //-- La salida tx la registramos
 always @(posedge clk)
   TX <= so;
   
 //-- La señal de entrada txmit se pasa por un 
 //-- detector de flancos de subida para generar un tic
 reg q_re = 0;
 wire txmit_tic;
 
 always @(posedge clk)
   q_re <= txmit;
   
 assign txmit_tic = (~q_re & txmit);  
 
 
 
 //-- Estado de transmisor
 //-- 0: Parado
 //-- 1: Ocupado (transmitiendo)
 reg state = 0;
   
 always @(posedge clk)
   //-- Empieza la transmision: ocupado
   if (txmit)
     state <= 1'b1;
     
   //-- Acaba la transmision: libre    
   else if (ov)
     state <= 1'b0;
 
 //-- Contador de bits enviados
 reg [3:0] bits = 0;
 always @(posedge clk)
   //-- Si la cuenta ha terminado... volver a 0
   if (ov)
     bits <= 2'b00;
   else
     if (shift)
       bits <= bits + 1;
 
 //-- Comprobar si se ha transmitido el último bit (overflow)
 //-- 1 bit de start + 8 bits de datos + 1 bit de stop
 wire ov = (bits == 10);
 
 //-- La señal de ocupado es el estado del transmisor
 assign busy = state;
 
 //-- La señal de done es la de overflow pero retrasada un
 //-- periodo de reloj del sistema y que el biestable 
 //-- llegue al estado de parado antes de que se 
 //-- empiece otra transmision
 
 reg done=0;
 
 always @(posedge clk)
   done <= ov;
 
endmodule
//---- Top entity
module v73122e #(
 parameter v9b001a = 1
) (
 input [3:0] vdeb67e,
 output [3:0] va8f67e
);
 localparam p9 = v9b001a;
 localparam p10 = v9b001a;
 localparam p11 = v9b001a;
 localparam p12 = v9b001a;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w13;
 assign w6 = vdeb67e;
 assign va8f67e = w7;
 vd128d1 #(
  .v2fb6e5(p9)
 ) v462a62 (
  .vedbc89(w8),
  .v758f58(w13)
 );
 vd128d1 #(
  .v2fb6e5(p11)
 ) vb97618 (
  .v758f58(w2),
  .vedbc89(w3)
 );
 vd128d1 #(
  .v2fb6e5(p10)
 ) v6dcff3 (
  .v758f58(w4),
  .vedbc89(w5)
 );
 vd128d1 #(
  .v2fb6e5(p12)
 ) vb50fef (
  .vedbc89(w0),
  .v758f58(w1)
 );
 vc4f23a v4515a9 (
  .v64d863(w0),
  .vda577d(w3),
  .v3f8943(w5),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v711731 (
  .v03aaf0(w1),
  .vf8041d(w2),
  .vee8a83(w4),
  .v11bca5(w7),
  .vd84a57(w13)
 );
endmodule

//---------------------------------------------------
//-- pull-up-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 4 FPGA internal pull-ups
//---------------------------------------------------
//---- Top entity
module vd128d1 #(
 parameter v2fb6e5 = 1
) (
 input vedbc89,
 output v758f58
);
 localparam p2 = v2fb6e5;
 wire w0;
 wire w1;
 assign w0 = vedbc89;
 assign v758f58 = w1;
 vd128d1_v34955f #(
  .ON(p2)
 ) v34955f (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- Pull-upx1_ICE40
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Pull-up_ICE40:: FPGA internal pull-up configuration on the input port. ICE40 FPGA family
//---------------------------------------------------

module vd128d1_v34955f #(
 parameter ON = 0
) (
 input i,
 output o
);
 // 1-Pull up
 
 //-- Place the IO block, configured as  
 //-- input with pull-up
 SB_IO
   #(
     .PIN_TYPE(6'b 1010_01),
     
     //-- The pull-up is activated or not
     //-- depeding on the ON parameter
     .PULLUP(ON)
     
   ) input_pin (
 
     //--- Input pin
     .PACKAGE_PIN(i),
     
     //-- Block output
     .D_IN_0(o),
     
     //-- Configured as input
     .OUTPUT_ENABLE(1'b0),
     
     //-- Not used
     .D_OUT_0(1'b0)
   );
endmodule
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule

module main_vb78d31 (
 input [3:0] col,
 input Clk_i,
 output [3:0] row,
 output [7:0] Value,
 output txmit
);
 
 // reg [3:0] col;
 reg [3:0] row = 4'b1110;
 reg txmit = 1;
 
 always @(posedge Clk_i) begin
     row <= {row[2:0], row[3]};
     Value <= {row, col};
     txmit <= !txmit;
 end
 
endmodule
