// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input [3:0] vf8607e,
 input v96ed7b,
 output [7:0] v819947
);
 wire [0:3] w0;
 wire [0:3] w1;
 wire [0:7] w2;
 wire w3;
 assign w0 = vf8607e;
 assign v819947 = w2;
 assign w3 = v96ed7b;
 v73122e ve71901 (
  .vdeb67e(w0),
  .va8f67e(w1)
 );
 main_v225efa v225efa (
  .ind(w1),
  .led(w2),
  .Clk_i(w3)
 );
endmodule

//---- Top entity
module v73122e #(
 parameter v9b001a = 1
) (
 input [3:0] vdeb67e,
 output [3:0] va8f67e
);
 localparam p9 = v9b001a;
 localparam p10 = v9b001a;
 localparam p11 = v9b001a;
 localparam p12 = v9b001a;
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w5;
 wire [0:3] w6;
 wire [0:3] w7;
 wire w8;
 wire w13;
 assign w6 = vdeb67e;
 assign va8f67e = w7;
 vd128d1 #(
  .v2fb6e5(p9)
 ) v462a62 (
  .vedbc89(w8),
  .v758f58(w13)
 );
 vd128d1 #(
  .v2fb6e5(p11)
 ) vb97618 (
  .v758f58(w2),
  .vedbc89(w3)
 );
 vd128d1 #(
  .v2fb6e5(p10)
 ) v6dcff3 (
  .v758f58(w4),
  .vedbc89(w5)
 );
 vd128d1 #(
  .v2fb6e5(p12)
 ) vb50fef (
  .vedbc89(w0),
  .v758f58(w1)
 );
 vc4f23a v4515a9 (
  .v64d863(w0),
  .vda577d(w3),
  .v3f8943(w5),
  .v985fcb(w6),
  .v4f1fd3(w8)
 );
 v84f0a1 v711731 (
  .v03aaf0(w1),
  .vf8041d(w2),
  .vee8a83(w4),
  .v11bca5(w7),
  .vd84a57(w13)
 );
endmodule

//---------------------------------------------------
//-- pull-up-x04
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 4 FPGA internal pull-ups
//---------------------------------------------------
//---- Top entity
module vd128d1 #(
 parameter v2fb6e5 = 1
) (
 input vedbc89,
 output v758f58
);
 localparam p2 = v2fb6e5;
 wire w0;
 wire w1;
 assign w0 = vedbc89;
 assign v758f58 = w1;
 vd128d1_v34955f #(
  .ON(p2)
 ) v34955f (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- Pull-upx1_ICE40
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Pull-up_ICE40:: FPGA internal pull-up configuration on the input port. ICE40 FPGA family
//---------------------------------------------------

module vd128d1_v34955f #(
 parameter ON = 0
) (
 input i,
 output o
);
 // 1-Pull up
 
 //-- Place the IO block, configured as  
 //-- input with pull-up
 SB_IO
   #(
     .PIN_TYPE(6'b 1010_01),
     
     //-- The pull-up is activated or not
     //-- depeding on the ON parameter
     .PULLUP(ON)
     
   ) input_pin (
 
     //--- Input pin
     .PACKAGE_PIN(i),
     
     //-- Block output
     .D_IN_0(o),
     
     //-- Configured as input
     .OUTPUT_ENABLE(1'b0),
     
     //-- Not used
     .D_OUT_0(1'b0)
   );
endmodule
//---- Top entity
module vc4f23a (
 input [3:0] v985fcb,
 output v4f1fd3,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign vda577d = w2;
 assign v4f1fd3 = w3;
 assign w4 = v985fcb;
 vc4f23a_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .o2(w2),
  .o3(w3),
  .i(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Split-all: Split the 4-bits bus into its wires
//---------------------------------------------------

module vc4f23a_v9a2a06 (
 input [3:0] i,
 output o3,
 output o2,
 output o1,
 output o0
);
 assign o3 = i[3];
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module v84f0a1 (
 input vd84a57,
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [3:0] v11bca5
);
 wire w0;
 wire w1;
 wire w2;
 wire w3;
 wire [0:3] w4;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign w2 = vf8041d;
 assign w3 = vd84a57;
 assign v11bca5 = w4;
 v84f0a1_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .i2(w2),
  .i3(w3),
  .o(w4)
 );
endmodule

//---------------------------------------------------
//-- Bus4-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus4-Join-all: Join all the wires into a 4-bits Bus
//---------------------------------------------------

module v84f0a1_v9a2a06 (
 input i3,
 input i2,
 input i1,
 input i0,
 output [3:0] o
);
 assign o = {i3, i2, i1, i0};
 
endmodule

module main_v225efa (
 input [3:0] ind,
 input Clk_i,
 output [7:0] led
);
 
 reg [7:0] led;
 reg [31:0] co;
 reg [31:0] limit = 12000000;
 
 always @(posedge Clk_i) begin
     if (ind >= 4'b1000) begin
         if (co >= limit - 1) begin
             co <= 0;
             led <= ~led;
         end else begin
             co <= co + 1;
         end
     end else begin
         case (ind)
             4'b0000: begin
                 led <= 8'b00000001;
             end
             4'b0001: begin
                 led <= 8'b00000011;
             end
             4'b0010: begin
                 led <= 8'b00000111;
             end
             4'b0011: begin
                 led <= 8'b00001111;
             end
             4'b0100: begin
                 led <= 8'b00011111;
             end
             4'b0101: begin
                 led <= 8'b00111111;
             end
             4'b0110: begin
                 led <= 8'b01111111;
             end
             4'b0111: begin
                 led <= 8'b11111111;
             end
             default: begin
                 led <= 8'b00000000;
             end
         endcase
     end
 end
endmodule
