// Code generated by Icestudio 0.12

`default_nettype none

//---- Top entity
module main (
 input [2:0] v1ef187,
 input v04225a,
 output [3:0] v42eeef,
 output [6:0] v75d009
);
 wire w0;
 wire w1;
 wire [0:3] w2;
 wire [0:2] w3;
 wire [0:2] w4;
 wire [0:2] w5;
 wire [0:3] w6;
 wire [0:6] w7;
 assign w1 = v04225a;
 assign v42eeef = w2;
 assign w3 = v1ef187;
 assign v75d009 = w7;
 assign w5 = w4;
 assign w6 = w2;
 main_v873e9c v873e9c (
  .Clk_i(w0),
  .DCBA(w2),
  .SUT(w4)
 );
 vc71757 vebf617 (
  .v2efea4(w0),
  .v0daa9e(w1)
 );
 v959ecb v162edf (
  .vf9ac3c(w3),
  .vcd99f9(w4)
 );
 ve1d5dc v16a07a (
  .v240e0a(w6),
  .vb5e893(w7)
 );
endmodule

//---- Top entity
module vc71757 #(
 parameter v245bef = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p1 = v245bef;
 wire w0;
 wire w2;
 assign w0 = v0daa9e;
 assign v2efea4 = w2;
 v435b29 #(
  .v100e1b(p1)
 ) v81886f (
  .v0daa9e(w0),
  .v2efea4(w2)
 );
endmodule

//---------------------------------------------------
//-- Prescaler22
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 22-bits prescaler
//---------------------------------------------------
//---- Top entity
module v435b29 #(
 parameter v100e1b = 22
) (
 input v0daa9e,
 output v2efea4
);
 localparam p2 = v100e1b;
 wire w0;
 wire w1;
 assign v2efea4 = w0;
 assign w1 = v0daa9e;
 v435b29_vac7386 #(
  .N(p2)
 ) vac7386 (
  .clk_out(w0),
  .clk_in(w1)
 );
endmodule

//---------------------------------------------------
//-- PrescalerN
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Parametric N-bits prescaler
//---------------------------------------------------

module v435b29_vac7386 #(
 parameter N = 0
) (
 input clk_in,
 output clk_out
);
 //-- Number of bits of the prescaler
 //parameter N = 22;
 
 //-- divisor register
 reg [N-1:0] divcounter;
 
 //-- N bit counter
 always @(posedge clk_in)
   divcounter <= divcounter + 1;
 
 //-- Use the most significant bit as output
 assign clk_out = divcounter[N-1];
endmodule
//---- Top entity
module v959ecb #(
 parameter v9b001a = 1
) (
 input [2:0] vf9ac3c,
 output [2:0] vcd99f9
);
 localparam p0 = v9b001a;
 localparam p5 = v9b001a;
 localparam p7 = v9b001a;
 wire w1;
 wire w2;
 wire w3;
 wire w4;
 wire w6;
 wire w8;
 wire [0:2] w9;
 wire [0:2] w10;
 assign w9 = vf9ac3c;
 assign vcd99f9 = w10;
 vd128d1 #(
  .v2fb6e5(p5)
 ) v85861e (
  .v758f58(w3),
  .vedbc89(w4)
 );
 vd128d1 #(
  .v2fb6e5(p7)
 ) v4ea693 (
  .v758f58(w6),
  .vedbc89(w8)
 );
 vd128d1 #(
  .v2fb6e5(p0)
 ) vef7256 (
  .vedbc89(w1),
  .v758f58(w2)
 );
 v2b9b8c v371929 (
  .v03aaf0(w2),
  .vf8041d(w3),
  .vee8a83(w6),
  .ve52f8a(w10)
 );
 v9a2795 va58442 (
  .v64d863(w1),
  .vda577d(w4),
  .v3f8943(w8),
  .vdee7c7(w9)
 );
endmodule

//---------------------------------------------------
//-- pull-up-x03
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- 3 FPGA internal pull-ups
//---------------------------------------------------
//---- Top entity
module vd128d1 #(
 parameter v2fb6e5 = 1
) (
 input vedbc89,
 output v758f58
);
 localparam p2 = v2fb6e5;
 wire w0;
 wire w1;
 assign w0 = vedbc89;
 assign v758f58 = w1;
 vd128d1_v34955f #(
  .ON(p2)
 ) v34955f (
  .i(w0),
  .o(w1)
 );
endmodule

//---------------------------------------------------
//-- Pull-upx1_ICE40
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Pull-up_ICE40:: FPGA internal pull-up configuration on the input port. ICE40 FPGA family
//---------------------------------------------------

module vd128d1_v34955f #(
 parameter ON = 0
) (
 input i,
 output o
);
 // 1-Pull up
 
 //-- Place the IO block, configured as  
 //-- input with pull-up
 SB_IO
   #(
     .PIN_TYPE(6'b 1010_01),
     
     //-- The pull-up is activated or not
     //-- depeding on the ON parameter
     .PULLUP(ON)
     
   ) input_pin (
 
     //--- Input pin
     .PACKAGE_PIN(i),
     
     //-- Block output
     .D_IN_0(o),
     
     //-- Configured as input
     .OUTPUT_ENABLE(1'b0),
     
     //-- Not used
     .D_OUT_0(1'b0)
   );
endmodule
//---- Top entity
module v2b9b8c (
 input vf8041d,
 input vee8a83,
 input v03aaf0,
 output [2:0] ve52f8a
);
 wire w0;
 wire w1;
 wire [0:2] w2;
 wire w3;
 assign w0 = vee8a83;
 assign w1 = v03aaf0;
 assign ve52f8a = w2;
 assign w3 = vf8041d;
 v2b9b8c_v9a2a06 v9a2a06 (
  .i1(w0),
  .i0(w1),
  .o(w2),
  .i2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus3-Join-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus3-Join-all: Joint three wires into a 3-bits Bus
//---------------------------------------------------

module v2b9b8c_v9a2a06 (
 input i2,
 input i1,
 input i0,
 output [2:0] o
);
 assign o = {i2, i1, i0};
 
endmodule
//---- Top entity
module v9a2795 (
 input [2:0] vdee7c7,
 output vda577d,
 output v3f8943,
 output v64d863
);
 wire w0;
 wire w1;
 wire [0:2] w2;
 wire w3;
 assign v3f8943 = w0;
 assign v64d863 = w1;
 assign w2 = vdee7c7;
 assign vda577d = w3;
 v9a2795_v9a2a06 v9a2a06 (
  .o1(w0),
  .o0(w1),
  .i(w2),
  .o2(w3)
 );
endmodule

//---------------------------------------------------
//-- Bus3-Split-all
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- Bus3-Split-all: Split the 3-bits bus into three wires
//---------------------------------------------------

module v9a2795_v9a2a06 (
 input [2:0] i,
 output o2,
 output o1,
 output o0
);
 assign o2 = i[2];
 assign o1 = i[1];
 assign o0 = i[0];
endmodule
//---- Top entity
module ve1d5dc (
 input [3:0] v240e0a,
 output [6:0] vb5e893
);
 wire [0:6] w0;
 wire [0:3] w1;
 assign vb5e893 = w0;
 assign w1 = v240e0a;
 ve1d5dc_v056811 v056811 (
  .o(w0),
  .i(w1)
 );
endmodule

//---------------------------------------------------
//-- DisplayHEX
//-- - - - - - - - - - - - - - - - - - - - - - - - --
//-- DisplayHEX. Decodificador de binario a hexadecimal-7 segmentos. Ánodo común
//---------------------------------------------------

module ve1d5dc_v056811 (
 input [3:0] i,
 output [6:0] o
);
 reg o;
 
 always @(*)
 begin
 	case(i)
         4'h0: o = 7'b000_0001;
         4'h1: o = 7'b100_1111;
         4'h2: o = 7'b001_0010;
         4'h3: o = 7'b000_0110;
         4'h4: o = 7'b100_1100;
         4'h5: o = 7'b010_0100;
         4'h6: o = 7'b010_0000;
         4'h7: o = 7'b000_1111;
         4'h8: o = 7'b000_0000;
         4'h9: o = 7'b000_0100;
         4'hA: o = 7'b000_1000;
         4'hB: o = 7'b110_0000;
         4'hC: o = 7'b011_0001;
         4'hD: o = 7'b100_0010;
         4'HE: o = 7'b011_0000;
         4'hF: o = 7'b011_1000;
         default: o = 7'b111_1111;
 	endcase
 end
endmodule

module main_v873e9c (
 input [2:0] SUT,
 input Clk_i,
 output [3:0] DCBA
);
 
 reg [4:0] Value = 5'b00000;
 
 always @(posedge Clk_i) begin
     case(SUT)
         3'b000: Value <= (Value + 4'b0001) % 5'b10000;
         3'b001: Value <= (Value + 4'b0101) % 5'b10000;
         3'b010: begin
             Value <= Value - 4'b0001;
             if(Value == 5'b00000) begin
                 Value <= 5'b01111;
             end
         end
         3'b011: begin
             Value <= Value - 4'b0010;
             if(Value == 5'b00000) begin
                 Value <= 5'b01111;
             end
         end
         default:    Value <= 5'b01000;
     endcase
 end
 
 assign DCBA = Value[0:3];
endmodule
